# Generated by Django 5.0.1 on 2024-02-21 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='Короткий опис')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='картинка')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Пости',
            },
        ),
    ]
